POST http://192.168.0.80:9102/auth/register
Content-Type: application/json

{
  "username": "toutou",
  "passwrod": "1234",
  "email": "test_user@133.com",
  "phone": "15652251332"
}

###
# curl -X POST
#  http://192.168.0.80:9102/auth/login
#  -H 'Content-Type: application/json'
#  -d '{"username":"your_username","password":"your_password"}'
POST http://192.168.0.80:9102/auth/login
Content-Type: application/json

{
  "username": "test_user",
  "password": "password123"
}
###
POST http://192.168.0.80:9102/auth/login
Content-Type: application/json

{
"email": "test_user",
"password": "password123"
}

###
GET http://192.168.0.80:9102/user/profile/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzY1NDE2OTgzLCJ1c2VybmFtZSI6InRlc3RfdXNlciJ9.b2WCfVU2zfZrzlgMPjYuGw1MVEoKPjaeCdGbj1zHsRM

###
GET http://192.168.0.80:9102/user/roles/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzY1NDE2OTgzLCJ1c2VybmFtZSI6InRlc3RfdXNlciJ9.b2WCfVU2zfZrzlgMPjYuGw1MVEoKPjaeCdGbj1zHsRM
###
GET http://192.168.0.80:9102/user/permissions/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzY1NDE2OTgzLCJ1c2VybmFtZSI6InRlc3RfdXNlciJ9.b2WCfVU2zfZrzlgMPjYuGw1MVEoKPjaeCdGbj1zHsRM
###
POST http://192.168.0.80:9102/favorite/1/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzY1NDE4MjI5LCJ1c2VybmFtZSI6InRlc3RfdXNlciJ9.PHyRFm0fIgV_HU31XTIiPw0BvYSsHBzC0bDTL_MWqo0
###
GET http://192.168.0.80:9102/favorite/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzY1NDE4MjI5LCJ1c2VybmFtZSI6InRlc3RfdXNlciJ9.PHyRFm0fIgV_HU31XTIiPw0BvYSsHBzC0bDTL_MWqo0
###
DELETE http://192.168.0.80:9102/favorite/1/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzY1NDE4MjI5LCJ1c2VybmFtZSI6InRlc3RfdXNlciJ9.PHyRFm0fIgV_HU31XTIiPw0BvYSsHBzC0bDTL_MWqo0

###
PUT http://192.168.0.80:9102/user/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzY1NTE5MDQ5LCJ1c2VybmFtZSI6InRlc3RfdXNlciJ9.KQGLJagdHsqkcpCWgA3WhMCtAXn23dVzUCam7mRSn4c

{
  "nickname": "toutou",
  "email": "test_user@156.com",
  "username": "aaa",
  "oldPassword": "Aa123456",
  "newPassword": "Aa123456",
  "phone": "15752251332",
  "avatar": "https://avatars.githubusercontent.com/u/1?v=4",
  "gender": "0"
}
